### ISSUE TITLE
Use of a prefer format parameter to sort Aims format lists for a database

### ISSUE THREAD

**Issue by Hboni** [brainvisa/axon#7] opened 2019-04-03 10:08 UTC
The initial problem is when a picture has to be saved using a `WriteDiskItem`, the format use is the first declared in the Signature of the process. But it can be good to have the possibility to choose if we prefer to save in compressed or uncompressed format.
To do that, some parameters in preferences can allow user to choose prefered format. This parameter can be database-specific, and so, the parameter can be in the *expert settings* of each database. It can be a list of Aims format which has to be ordered in prefered format for the database.

**Comment by Hboni** [comment] 2019-04-05 13:19
I think I see what I want to do and where I can do it, but I don't really know how. 
In *python/brainvisa/configuration/databases_configuration.py*, `ExpertDatabaseSettings` UI is created using `Signature`.
@brainvisa/release I wanted to know if it's possible to add a parameter with a specific widget in the layout, or using `Signature` doesn't allow to make this modification ? 
I wanted to use a widget like for the organisation of databases order (a `QListWidget`)?

**Comment by denisri** [comment] 2019-04-05 14:16
Signature has its GUI automatically built from its elements types, but there used to be a way to specialize the GUI on a per-element basis, if needed. Note that his is a different kind of Signature from the signatures in processes: it was designed to be a future replacement for it, but was never done since we started Capsul, based on traits, after that. It is still used in settings. I don't remember at all how the GUI specialization used to work, or if it still works since this feature has not been used much. Yann is the guy who could remember (since he wrote this system). Other wise I have to look at the code.

**Comment by Hboni** [comment] 2019-04-05 14:40
Ok, it doesn't seems easy, for a first version, I can use a `ListOf(String())`, we will upgrade it with a list later, maybe with Yann, I don't want to take your precious time. 
Thanks for the answer !

**Comment by denisri** [comment] 2019-04-05 18:54
Actually it's not a ListOf(String) since it is a different signature API as processes: it would be a Sequence(Unicode).
Well, I have started to so something in a feature branch "formats": https://github.com/brainvisa/axon/commit/40407264f4fee7b4179ae6460215f90b960fd35a
I didn't have time to finish yet. The idea is that a signature item class (inheriting soma.signature.signature.DataType) may provide a GUI widget, just by declaring a class with the same name suffixed by "_Qt4GUI" and inheriting soma.qt4gui.api.Qt4Gui (it should maybe be located in a subtirectory "qt4gui", I didn't check that).

**Comment by denisri** [comment] 2019-04-07 22:07
In the feature branch "formats" it is now possible to sort formats in the expert database settings GUI. They are saved in each database in the "database_settings.minf" file. Now these sorted formats lists may  be used to actually sort formats used by processes.
However I have a doubt if all processes should have their formats sorted like this, or if some process should still force their preferred ones...?

**Comment by Hboni** [comment] 2019-04-08 12:10
So now the `AimsWritableFormats` that is used in processes use the formats list in "database_settings.minf" or not yet ? (I'm going to try but I've got types issues when launching BV)
I think it's better to have the same formats order for all the processes. If we want to have the possibility to have the original and the new formats order, we can rename the database-specific one with another name like `AimsWritableFormatsPrefered`, and so we can use `AimsWritableFormats` for processes which need to keep the initial order (but it seems complicating)

**Comment by denisri** [comment] 2019-04-08 15:46
No, this is not done yet. The branch in its current state just allows to edit and save a list of formats with databases, but it doesn't change anything in the aimsGlobals formats list yet. 
Anyway as the order is database-specific, it cannot be stored in a single global list: it should be either stored in a database-indexed dictionary, or re-sorted on-the-fly with each use (which might slow the system somewhat). There are still questions on how to use them I think.

**Comment by denisri** [comment] 2019-04-16 12:41
I have just pushed improvements on the formats branch: it should now take into account database-specific formats ordering. However, they are useful only when a WriteDiskItem has to choose a format withoud being the destination of a link from a file with a compatible format, otherwise the former rule (output format = input format) still applies.

**Comment by Hboni** [comment] 2019-04-16 12:52
It sounds great for me ! 
I just wonder what if an output is linked to another file, the output use the preferred order formats, and the other file has only one format (which is not the first choice of the output format). When the output want to find the file, does it take account of the other format as well ?

**Comment by denisri** [comment] 2019-04-16 13:57
When (for instance) an input (I) is linked to an output (O), then I has to be found first, of course. Thus it already has a single format. The rule that was used up to now, and which I didn't break in my modifications, is that if the format of I is allowed for O, then O will get that format. If this first rule doesn't apply (if O doesn't allow the format of I, for instance if O is of a different nature), then it will get the first allowed format in the ordered list associated to the database it belongs.
So my modif is maybe not what you expect. It is technically possible to disable the first rule (O gets the format of I) but I'm not sure this is always what users want/expect. Or maybe this could be an additional setting (another flag in database settings?)

**Comment by Hboni** [comment] 2019-04-18 14:16
After checkout axon into `formats` branch, I wanted to try to fill a pipeline, but I quicly had this issue : 

> `Traceback (most recent call last):
>   File "/home/hb255304/brainvisa/build/bug_fix/python/brainvisa/processing/qt4gui/neuroProcessesGUI.py", line 1932, in updateParameterValue
>     setattr(self.parameterized, name, value)
>   File "/home/hb255304/brainvisa/build/bug_fix/python/brainvisa/processes.py", line 955, in __setattr__
>     self.setValue(name, value, default)
>   File "/home/hb255304/brainvisa/build/bug_fix/python/brainvisa/processes.py", line 989, in setValue
>     self._parameterHasChanged(name, newValue)
>   File "/home/hb255304/brainvisa/build/bug_fix/python/brainvisa/processes.py", line 896, in _parameterHasChanged
>     parameterized.setValue(attribute, v)
>   File "/home/hb255304/brainvisa/build/bug_fix/python/brainvisa/processes.py", line 989, in setValue
>     self._parameterHasChanged(name, newValue)
>   File "/home/hb255304/brainvisa/build/bug_fix/python/brainvisa/processes.py", line 896, in _parameterHasChanged
>     parameterized.setValue(attribute, v)
>   File "/home/hb255304/brainvisa/build/bug_fix/python/brainvisa/processes.py", line 989, in setValue
>     self._parameterHasChanged(name, newValue)
>   File "/home/hb255304/brainvisa/build/bug_fix/python/brainvisa/processes.py", line 874, in _parameterHasChanged
>     parameterized.setValue(attribute, newValue)
>   File "/home/hb255304/brainvisa/build/bug_fix/python/brainvisa/processes.py", line 981, in setValue
>     newValue = self.signature[name].findValue(value)
>   File "/home/hb255304/brainvisa/build/bug_fix/python/brainvisa/data/readdiskitem.py", line 438, in findValue
>     _debug=_debug))
>   File "/home/hb255304/brainvisa/build/bug_fix/python/brainvisa/data/readdiskitem.py", line 649, in _findValues
>     for item in self.database.createDiskItems(selection, _debug=_debug, exactType=self.exactType, **requiredAttributes):
>   File "/home/hb255304/brainvisa/build/bug_fix/python/brainvisa/data/sqlFSODatabase.py", line 2357, in createDiskItems
>     for item in database.createDiskItems(selection, _debug=_debug, exactType=exactType, **required):
>   File "/home/hb255304/brainvisa/build/bug_fix/python/brainvisa/data/sqlFSODatabase.py", line 2043, in createDiskItems
>     format.name)  # get corresponding file format
>   File "/home/hb255304/brainvisa/build/bug_fix/python/brainvisa/data/fileformats.py", line 102, in getFormat
>     raise KeyError(_('Unknown format "%s"') % (format, ))
> KeyError: 'Unknown format "JSON file"'`

It seems that it only search on the preferred format list !?

**Comment by denisri** [comment] 2019-04-19 12:15
The line numbers in your traceback do not correspond to those in my source files, so I suspect your branch has not been updated ? Did you pull the branch ?

**Comment by Hboni** [comment] 2019-04-23 07:49
Oh yeah, I didn't pull the branch, it's better now !

**Comment by Hboni** [comment] 2019-04-23 09:17
I tested the *spm12 - Segment* process, when I change the order of my database, I have to close and open Brainvisa to take account of the change.

**Comment by Hboni** [comment] 2019-04-23 15:24
After that, I also tried a pipeline which call processes, and I have the error : 
`'ReadDiskItem' object has no attribute 'preferredFormat' `
with more detailled error : 

> `processes.py (3269) in _processExecution: `
> `result = process.execution(self)`
> `SPM12Segment.py (623) in execution: `
> `batch_location=self.batch_location)`
> `processes.py (2986) in runProcess: `
> `result = self._processExecution(_process, None)`
> `processes.py (3223) in _processExecution: `
> `tmp = _getConvertedValue(v, p.contentType)`
> `processes.py (3158) in _getConvertedValue: `
> `formats = [ p.preferredFormat ] \`

**Comment by denisri** [comment] 2019-04-24 10:14
I have pushed a fix for the preferredFormat issue.

**Comment by Hboni** [comment] 2019-04-25 15:37
The preferredFormat issue seems to be fixed ! :+1:

**Comment by denisri** [comment] 2019-05-29 16:59
fixed after 9b2043db4d5f915998c4d06100c9e939bad0afca

**Closed by denisri** 2019-05-29 16:59 UTC
Labels: enhancement
